### ISSUE TITLE
Flask migrate only works for initial migration

### ISSUE THREAD

**Issue by siparker** [app-generator/flask-soft-ui-dashboard-pro#1]
Flask migrate provides the initial migration when the app is first run to create all database tables. This works well and creates the SQlite db and the tables within it.

When used in production the normal workflow is to create a migration using flask migrate and to run this migration on the production db. 

expected to do

flask db init # this noted the current state and the initial version of the db and adds a version number to the database  

you then make changes to the models.

flask db migrate # this checks the models and makes a migration sql script to update the db to match the new model.

flask db upgrade # this applies the migration to the db adding or removing tables as per your changes to the models.

How do we utilise the flask db command within your app.

**Comment by app-generator** [comment]
Hello @siparker,

The reported issue is visible because of some SQLite limitations: 
- [Fixing ALTER TABLE errors with Flask-Migrate and SQLite](https://blog.miguelgrinberg.com/post/fixing-alter-table-errors-with-flask-migrate-and-sqlite)
- [Batch migrations for SQLite](https://alembic.sqlalchemy.org/en/latest/batch.html#dealing-with-constraints)

To have a successful migration using SQLite, please do the following workaround: 
- update `run.py` and enable the `batch` mode: 
```python
...
app = create_app( app_config ) 
Migrate(app, db, render_as_batch=True) # <-- UPDATED
...
```

- Update initial migration `flask db init`
- Generate SQL `flask db migrate`
- Apply changes `flask db update`

Update your models - We did a test with a new field `info` on the `User` table
- Generate SQL `flask db migrate`
- Edit the MIgration script and comment on the lines related to `create_unique_constraint`

```python
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.String(), nullable=True))
        #batch_op.create_unique_constraint(None, ['info'])                              # <-- COMMENT 

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='unique')                              # <-- COMMENT
        batch_op.drop_column('info')
```

- Execute the migration

Our suggestion is to use a stronger DBMS engine like MySql or PostgreSQL.
